#! /bin/python

# Not meant to be imported, will throw error
if __name__ != "__main__":
    dont_import_this_script

# created by start-build.sh
import tools

### EVERYTHING PAST THIS LINE IS GENERATED BY generate.js
