#! /bin/python

# Not meant to be imported, will throw error
if __name__ != "__main__":
    dont_import_this_script

# created by start-build.sh
import tools

### EVERYTHING PAST THIS LINE IS GENERATED BY generate.js

# {"cmd":"make","cwd":"/code/PATH/"}
tools.run("/code/PATH/", "make")

# {"cmd":"./build.sh","cwd":"/code/hello_world.c_maker/"}
tools.run("/code/hello_world.c_maker/", "./build.sh")

# {"cmd":"./hello_world.c_maker > /code/hello_world.c","cwd":"/code/hello_world.c_maker/"}
tools.run("/code/hello_world.c_maker/", "./hello_world.c_maker > /code/hello_world.c")

# {"cmd":"gcc -o hello_world hello_world.c -ansi -O3","cwd":"/code/"}
tools.run("/code/", "gcc -o hello_world hello_world.c -ansi -O3")
