name: Test Build Time

on: # button click and PR to main
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps: # should be self explanatory
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Install docker-compose
        run: |
          sudo apt-get install -y docker-compose
      - name: Build and record time
        run: |
          sudo bash github_runner.sh
      - name: Print results to log
        run: |
          cat results.md
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results.md
          path: results.md
